// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    acompanhamento: {
        name: "acompanhamento";
        parameters: Record<string, never>;
        result: Array<{
          /** Vendedor responsável pela carteira do cliente — quem faz a ligação. */
          vendedor: string;
          /** @sqlType BIGINT */
          na_fila: number;
          /** @sqlType BIGINT */
          trabalhados: number;
          /** @sqlType BIGINT */
          vendeu: number;
          /** @sqlType BIGINT */
          vai_pensar: number;
          /** @sqlType BIGINT */
          sem_interesse: number;
          /** @sqlType BIGINT */
          nao_atendeu: number;
        }>;
      };
    fila: {
        name: "fila";
        parameters: {
          /** STRING - use sql.string() */
          vendedor: SQLStringMarker;
        };
        result: Array<{
          /** Vendedor responsável pela carteira do cliente — quem faz a ligação. */
          vendedor: string;
          /** Posição do cliente na lista do vendedor, 1 = maior prioridade (maior score). */
          ordem: number;
          /** Cliente a ser contatado. */
          cliente_id: number;
          /** Razão social do cliente. */
          razao_social: string;
          /** Cidade do cliente. */
          cidade: string;
          /** UF do cliente. */
          uf: string;
          /** Probabilidade de compra em 7 dias, do modelo @prod (0 a 1). */
          score: number;
          /** Faixa de prioridade do score: Fria, Morna, Quente ou Muito quente. */
          faixa: string;
          /** Ticket médio histórico do cliente. */
          ticket_medio: number;
          /** Por que este cliente está na fila, em português, com os números dele — nunca nulo. */
          motivo: string;
          /** SKU da marca preferida do cliente que ele não compra há mais de 90 dias, com o saldo do snapshot mais recente de estoque — NULL quando não há sugestão elegível. */
          sugestao: string;
          /** Desfecho da ligação: vendeu, vai_pensar, sem_interesse ou nao_atendeu — validado pelo enum do servidor do app, não por CHECK constraint aqui. */
          retorno_status: string;
          /** Texto livre do vendedor sobre a ligação, opcional. */
          retorno_comentario: string;
        }>;
      };
    kpis_semana: {
        name: "kpis_semana";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType BIGINT */
          contatos: number;
          /** @sqlType BIGINT */
          vendedores: number;
          /** @sqlType DOUBLE */
          receita_esperada: number;
          /** @sqlType DATE */
          referencia: string;
          /** @sqlType STRING */
          versao: string;
          /** @sqlType DOUBLE */
          lift_top200: number;
          /** @sqlType BIGINT */
          acertos_top200: number;
          /** @sqlType DOUBLE */
          taxa_base: number;
          /** @sqlType BIGINT */
          ja_trabalhados: number;
          /** @sqlType BIGINT */
          viraram_pedido: number;
        }>;
      };
    vendedores: {
        name: "vendedores";
        parameters: Record<string, never>;
        result: Array<{
          /** Vendedor responsável pela carteira do cliente — quem faz a ligação. */
          vendedor: string;
          /** @sqlType BIGINT */
          contatos: number;
        }>;
      };
  }
}
